#Run it with: docker compose up
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "192.168.86.195:53:53/tcp" #Replace with your local IP, otherwise it tries to bind to 127.0.0.1, which is already in use by systemd-resolve (The OS DNS resolver)
      - "192.168.86.195:53:53/udp" #Replace with your local IP, otherwise it tries to bind to 127.0.0.1, which is already in use by systemd-resolve (The OS DNS resolver)
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8090:80/tcp"
    environment:
      TZ: 'Europe/Copenhagen'
      WEBPASSWORD: 'password' # Replace with your password
      DNSMASQ_LISTENING: 'all'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
      - CAP_NET_BIND_SERVICE
    restart: unless-stopped
