version: "3.5"
services:
  minecraft:
    image: eclipse-temurin:17
    ports:
      - "25565:25565/tcp" #server
      - "25575:25575/tcp" #rcon
    volumes:
      - "$PWD/server:/wrk"
    working_dir: /wrk
    restart: "on-failure"
    command: "java -Xms512m -Xmx1g -XX:+UseG1GC -jar fabric-server-mc.1.18.2-loader.0.14.10-launcher.0.11.1.jar nogui"
